COMMON_SOURCES = ./src/Engine.cpp \
    ./src/EngineMain.cpp \
    ./src/Demo/DemoScene.cpp \
    ./src/Assets/AssetLibrary.cpp \
    ./src/Rendering/ScenePresenter.cpp \
    ./src/Rendering/SceneTransforms.cpp \
    ./src/Runtime/AudioService.cpp \
    ./src/Runtime/GameplaySystems.cpp \
    ./src/Runtime/Globals.cpp \
    ./src/Event.cpp \
    ./src/TimerCreator.cpp \
    ./src/VertexData.cpp \
    ./src/Systems/CollisionSystem.cpp \
    ./src/Systems/AnimationSystem.cpp \
    ./src/Systems/PhysicsSystem.cpp \
    ./src/ComponentManager.cpp \
    ./src/EntityManager.cpp \
    ./src/Systems/MovementSystem.cpp \
    ./src/SystemManager.cpp \
    ./src/Systems/ProjectileSystem.cpp \
    ./src/SoundEngineFactory.cpp \
    ./src/GraphicAPI/Vulkan.cpp \
    ./src/GraphicAPI/VulkanDevice.cpp \
    ./src/GraphicAPI/VulkanMemory.cpp \
    ./src/GraphicAPI/VulkanDescriptors.cpp \
    ./src/GraphicAPI/VulkanFrame.cpp \
    ./src/GraphicAPI/VulkanOverlay.cpp \
    ./src/GraphicAPI/VulkanShadows.cpp \
    ./src/TextureManager.cpp \
    ./src/WavefrontObjParser.cpp \
    ./src/MeshManager.cpp \
    ./src/JsonParser.cpp \
    ./textures/chelik.cpp \
    ./textures/witch.cpp \
    ./textures/crosshair.cpp \
    ./textures/gray.cpp \
    ./textures/container2.cpp \
    ./textures/container2_specular.cpp \
    ./src/Systems/DamageSystem.cpp \
    ./src/Systems/EnemySystem.cpp \
    ./textures/fontAtlas.cpp \
    ./textures/inventorySlot.cpp \
    ./src/Systems/ItemSystem.cpp \
    ./src/ProceduralLevelGeneratingSystem.cpp \
    ./textures/tileset.cpp \
    ./src/Systems/InventorySystem.cpp \
    ./src/GraphicAPI/VkBuilders.cpp \
    ./src/GraphicAPI/RenderData.cpp \
    ./src/GraphicAPI/RenderConfig.cpp \
    ./src/GraphicAPI/VkDebugUtils.cpp \
    ./src/ThreadPool.cpp \
    ./src/ArchetypedECS/ArchECS_Utils.cpp \
    ./src/ArchetypedECS/ArchECS_World.cpp \
    ./src/ArchetypedECS/ArchetypeEntityManager.cpp \
    ./src/ArchetypedECS/ArchetypeInterface.cpp \
    ./src/Systems/SpatialGridSystem.cpp \
    ./src/Common/CommonFunctions.cpp
