#+title: Grey Lane Vertex Machine (GLVM) documentation
#+author: Yuriorkis_Scream

* Common engine description
GLVM engine based on simple entity component system (ECS) that using
sparse arrays provided cache friendly data. ECS gives opportunity to
easily add or remove new systems that working with components. Common
working with GLVM based on creating of three super objects. One of them -
is instance of engine itself, and we also need EntityManager and
ComponentManager for using ECS system. Most of common GLVM object is
located in special namespaces.


* Common GLVM functions
- Create engine instance
  This is main super object of GLVM engine. Actualy its engine itself.
#+begin_src c++
  GLVM::core::Engine* GLVM = GLVM::core::Engine::GetInstance();
#+end_src

- Create entity manager instance
  With this super object you can manage entities.
#+begin_src c++
  GLVM::ecs::EntityManager* EntityManager = GLVM::ecs::EntityManager::GetInstance();
#+end_src

- Create component manager instance
  With this super object you can manage components.
#+begin_src c++
  GLVM::ecs::ComponentManager* ComponentManager  = GLVM::ecs::ComponentManager::GetInstance();
#+end_src

- Create entity
  All entities in GLVM exposed just as an integer number. When you call function CreateEntity
  you have to catch return value because its marked with [discard].
#+begin_src c++
  Entity uiPlayer = EntityManager->CreateEntity();
#+end_src

- Create component
  When you create entity you can link components to it with call to a function 
  CreateComponent<...place your list of components here...>(entity). This function is method of
  ComponentManager and it supports any number of components as template variadic parameters.
  Set all components you need in <> and pass target entity in ().
#+begin_src c++ 
  GLVM::ecs::ComponentManager->CreateComponent<GLVM::ecs::components::mesh,
											   GLVM::ecs::components::transform,
											   GLVM::ecs::components::rigidBody>(entity);
#+end_src

- Get component
  After you link components to any entity you can access each single component
  to change it for your purposes. This can be achieved with a call to a GetComponent function.
  This function is method of ComponentManager. When you call it, pass target entity to () and pass target
  component that linked to target entity to <>. 
#+begin_src c++ 
  *GLVM::ecs::ComponentManager->GetComponent<cm::transform>(uiPlayer) = {
	  .tPosition = { 5.7f, 10.0f, 7.0f }, .fScale = 0.1f };
#+end_src

- Loading textures
  GLVM takes raw data arrays for loading images. If you want to load some common format like PNG or JPG
  you need to transfer it to raw data. This can easily achived with simple tools like ImageMagick and XXD.
  Imagine that we have image called robot.png.

  1. Convert it to .dat format:

	 convert robot.png robot.dat

  2. Convert robot.dat to c-header file with static array inside:

	 xxd -i robot.dat > robot.h

  3. Place it in "textures" directory:

     mv robot.h /path/to/GLVM/textures

  4. Then just include this header in "SpritesData.hpp":

#+begin_src c++	 
      #ifndef SPRITES_DATA
      #define SPRITES_DATA

      #include "robot.h"

      #endif
#+end_src
  
  When its done you need to check actual height and width of your texture. Its easy to do with ImageMagick.
  Just give it robot.dat or robot.png with "identify" flag.
  
  5. magick identify robot.png

  Its give you simple output like:
  
  robot.png PNG 120x279 120x279+0+0 8-bit sRGB 44103B 0.000u 0:00.000

  We need numbers that have "x" between them. In this case this is 120x279. Width is 120 and height is 279.

  6.   Now we can call function "LoadTextureFromAddress" that load image to GLVM. You need to give it width, height,
	 length of image array and actual array that contain "robot.h".

#+begin_src c++
	[[maybe_unused]] ecs::TextureHandle robotTextureHandle = GLVM->LoadTextureFromAddress(120, 279, robot_dat_len, robot_dat);
#+end_src
