#include "Constants.hpp"

const char* pipelinesNames[14] {   ///< Pipelines names for debug
	"DIRECTIONAL_LIGHT_PIPELINE",
	"SPOT_LIGHT_PIPELINE",
	"POINT_LIGHT_PIPELINE",
	"HUD_PIPELINE",
	"FONT_PIPELINE",
	"HUD_SCREEN_PIPELINE",
	"UI_PIPELINE",
	"UI_ICONS_PIPELINE",
	"VIRTUAL_TEXTURES_PIPELINE",
	"MAIN_RENDER_PIPELINE",
	"SDF_PIPELINE",
	"COLLISIONS_DEBUG_PIPELINE",
	"SPACIAL_GRID_DEBUG_PIPELINE",
	"MATH_OBJECTS_DEBUG_PIPELINE",
};

